# Form implementation generated from reading ui file 'D:\pythonProject\KTLT_THAY_THANH\Chuong6_Library\LearnPandas\BT126\MainBT126.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 514)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(147, 147, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButtonLocClose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLocClose.setGeometry(QtCore.QRect(20, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonLocClose.setFont(font)
        self.pushButtonLocClose.setObjectName("pushButtonLocClose")
        self.tableWidgetResult = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetResult.setGeometry(QtCore.QRect(20, 180, 581, 261))
        self.tableWidgetResult.setObjectName("tableWidgetResult")
        self.tableWidgetResult.setColumnCount(0)
        self.tableWidgetResult.setRowCount(0)
        self.pushButtonNgay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonNgay.setGeometry(QtCore.QRect(190, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonNgay.setFont(font)
        self.pushButtonNgay.setObjectName("pushButtonNgay")
        self.lineEditInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditInput.setGeometry(QtCore.QRect(20, 100, 581, 20))
        self.lineEditInput.setObjectName("lineEditInput")
        self.pushButtonLocDateHighLow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLocDateHighLow.setGeometry(QtCore.QRect(390, 140, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonLocDateHighLow.setFont(font)
        self.pushButtonLocDateHighLow.setObjectName("pushButtonLocDateHighLow")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nguyễn Mậu Khánh Linh"))
        self.label.setText(_translate("MainWindow", "Phân tích dữ liệu"))
        self.pushButtonLocClose.setText(_translate("MainWindow", "Lọc Close"))
        self.pushButtonNgay.setText(_translate("MainWindow", "Lọc ngày"))
        self.pushButtonLocDateHighLow.setText(_translate("MainWindow", "Hiển thị Date, High, Low rồi Lọc"))
