# Form implementation generated from reading ui file 'D:\pythonProject\KTLT_THAY_THANH\Chuong6_Library\TichHopChart\MainWindown.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 576)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 581, 351))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutPlot = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlot.setObjectName("verticalLayoutPlot")
        self.verticalLayout_2.addLayout(self.verticalLayoutPlot)
        self.pushButtonBarChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBarChart.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.pushButtonBarChart.setObjectName("pushButtonBarChart")
        self.pushButtonLine = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLine.setGeometry(QtCore.QRect(160, 70, 101, 21))
        self.pushButtonLine.setObjectName("pushButtonLine")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(490, 70, 101, 21))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonPie = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPie.setGeometry(QtCore.QRect(320, 70, 101, 21))
        self.pushButtonPie.setObjectName("pushButtonPie")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Chart Visualization:"))
        self.pushButtonBarChart.setText(_translate("MainWindow", "Bar Chart"))
        self.pushButtonLine.setText(_translate("MainWindow", "Line Chart"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))
        self.pushButtonPie.setText(_translate("MainWindow", "Pie Chart"))
