# Form implementation generated from reading ui file 'D:\pythonProject\KTLT_THAY THANH\Chuong1_ham\Baitap\BT_giao dien\BAI11\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 450)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titlelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.Titlelabel.setGeometry(QtCore.QRect(30, 10, 381, 41))
        self.Titlelabel.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.Titlelabel.setObjectName("Titlelabel")
        self.ShowPNGpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ShowPNGpushButton.setGeometry(QtCore.QRect(140, 100, 121, 31))
        self.ShowPNGpushButton.setObjectName("ShowPNGpushButton")
        self.showGIFpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.showGIFpushButton.setGeometry(QtCore.QRect(270, 100, 121, 31))
        self.showGIFpushButton.setObjectName("showGIFpushButton")
        self.imageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(70, 180, 171, 151))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap("D:\\pythonProject\\KTLT_THAY THANH\\Chuong1_ham\\Baitap\\BT_giao dien\\BAI11\\../../../../../KTLT_THAY THANH/Chuong1_ham/Baitap/BT_giao dien/BAI11/images/s303.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.changeTextpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.changeTextpushButton.setGeometry(QtCore.QRect(30, 60, 75, 23))
        self.changeTextpushButton.setObjectName("changeTextpushButton")
        self.alignLeftpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.alignLeftpushButton.setGeometry(QtCore.QRect(240, 60, 75, 23))
        self.alignLeftpushButton.setObjectName("alignLeftpushButton")
        self.alignCenterpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.alignCenterpushButton.setGeometry(QtCore.QRect(330, 60, 75, 23))
        self.alignCenterpushButton.setObjectName("alignCenterpushButton")
        self.alignRightpushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.alignRightpushButton.setGeometry(QtCore.QRect(410, 60, 75, 23))
        self.alignRightpushButton.setObjectName("alignRightpushButton")
        self.fontSizepushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fontSizepushButton.setGeometry(QtCore.QRect(120, 60, 75, 23))
        self.fontSizepushButton.setObjectName("fontSizepushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nguyen Mau Khanh Linh - MainWindow"))
        self.Titlelabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#ff0000;\">Nguyễn Mậu Khánh Linh</span></p></body></html>"))
        self.ShowPNGpushButton.setText(_translate("MainWindow", "Show .PNG Format"))
        self.showGIFpushButton.setText(_translate("MainWindow", "Show .GIF Format"))
        self.changeTextpushButton.setText(_translate("MainWindow", "Change Text"))
        self.alignLeftpushButton.setText(_translate("MainWindow", "Align Left"))
        self.alignCenterpushButton.setText(_translate("MainWindow", "Align Center"))
        self.alignRightpushButton.setText(_translate("MainWindow", "Align Right"))
        self.fontSizepushButton.setText(_translate("MainWindow", "Font Size ++"))
