# Form implementation generated from reading ui file 'D:\pythonProject\KTLT_THAY_THANH\Chuong6_Library\BT117\BT117.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 426)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(80, 110, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCalculate.setFont(font)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.lineEditInputData = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditInputData.setGeometry(QtCore.QRect(80, 80, 241, 20))
        self.lineEditInputData.setObjectName("lineEditInputData")
        self.labelResults = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelResults.setGeometry(QtCore.QRect(70, 140, 271, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelResults.setFont(font)
        self.labelResults.setStyleSheet("background-color: rgb(195, 220, 230);\n"
"color: rgb(255, 255, 0);")
        self.labelResults.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.labelResults.setObjectName("labelResults")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nguyễn Mậu Khánh Linh - MainWindow117"))
        self.label.setText(_translate("MainWindow", "Enter Data (comma separated)"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate"))
        self.labelResults.setText(_translate("MainWindow", "Results:"))
